---
title: "Glucose dose effect on binomial aging, BY4742"
author: "h qin"
date: "June 28, 2016"
output: html_document
---

On June 28, 2016, Qin converted _BY4742.glucose.dose.20140712.r to Rmd. 

For binomial mortality model, see http://hongqinlab.blogspot.com/2013/12/binomial-mortailty-model.html . 


```{r}
#setwd("~/github/0.network.aging.prj.bmc/0a.rls.fitting")
setwd("/home/hqin/github/bmc_netwk_aging_manuscript/R1/0a.rls.fitting");
source("lifespan.r")
require(flexsurv)
```


The log-likelihood function for binomial mortality aging model
```{r}
llh.binomialMortality.single.run
```


RLS in different glucose doeses from Kaeberlein lab
```{r}
files = c(
  "BY4742_MATalpha_temp30_media_0.005% D_n299.csv",                   
  "BY4742_MATalpha_temp30_media_0.05% D_n4690.csv",                   
  "BY4742_MATalpha_temp30_media_0.1% D_n338.csv",                     
  "BY4742_MATalpha_temp30_media_0.5% D_n579.csv",                     
  "BY4742_MATalpha_temp30_media_YPD_n19930.csv"
);
```

Set up the dataframe to collect results
```{r}
output = data.frame(files); 
output$mean = NA; output$stddev = NA; output$CV=NA; 
output$R=NA; output$t0=NA; output$n=NA;
output$Rflex = NA; output$Gflex = NA; 
output$glucose = c(0.005, 0.05, 0.1, 0.5, 2.0)
```


```{r}
for( i in 1:5) {
  filename = paste('../klab_DR/', files[i], sep='')
  tb = read.csv(filename)
  summary(tb)
  output$mean[i]=mean(tb$rls)
  output$stddev[i]= sd(tb$rls)
  output$CV[i] = sd(tb$rls) / mean(tb$rls)
  
  fitGomp = flexsurvreg( formula=Surv(tb$rls) ~ 1, dist='gompertz')
  Rhat = fitGomp$res[2,1]; Ghat = fitGomp$res[1,1] 
  output$Rflex[i] = Rhat; output$Gflex[i]=Ghat; 
  
  #G = (n-1) / t0, so t0 = (n-1)/G
  nhat = 5; t0= (nhat-1)/Ghat; t0
  fitBinom = optim ( c(Rhat, t0, nhat),  llh.binomialMortality.single.run , lifespan=tb$rls, 
                method="L-BFGS-B", lower=c(1E-10,0.05,1E-1), upper=c(10,100,50) );  
  
  output[i, c("R", "t0", "n")] = fitBinom$par
  
    #  fitGomp2 = optim ( c(0.005, 0.08),  llh.G.single.run , lifespan=tb$rls,
   #                    method="L-BFGS-B", lower=c(1E-10,1E-2), upper=c(10,10) );  
  
  tb2 = calculate.mortality.rate(tb$rls)
  plot( tb2$s ~ tb2$t, main=files[i])
  plot( tb2$mortality.rate ~ tb2$t , main=files[i])
  plot( tb2$mortality.rate ~ tb2$t, log='y', main=paste( files[i], 'linear for Gompertz' ) )
  plot( tb2$mortality.rate ~ tb2$t, log='yx', main=paste(files[i],'linear for Weibull' ) )
}#i file loop

```

Here are the fitting results
```{r}
output
```

