---
title: "Fit mutant with binomial aging model"
author: "h qin"
date: '2017, May 2 ~ June '
output:
  pdf_document: default
  html_document: default
---

```{r}
rm(list=ls())
host = "Applejack" #"Ridgeside"
if (host == "AppleJack") {
 setwd("/Users/hqin/github/bmc_netwk_aging_manuscript/R1/1.mutants")
}
if (host == "Ridgeside") {
 setwd("/hong/hqin/github/bmc_netwk_aging_manuscript/R1/1.mutants")
}

library('flexsurv')
library('stringr')
source("../lifespan.r")
```

# parse the strains from files

Change mydir to either YPD or rls05D and run this code twice will generate the two output files in sandbox.  
```{r}
mydir = 'rlsYPD'
#mydir = 'rls05D'
files = list.files(path=paste(mydir,"/", sep=''), pattern="csv")

genotypes = c();
media = c();
for( i in 1:length(files)) {
 elements = unlist(str_split(files[i], "_"))
 genotypes = c(genotypes, elements[1])  
 media = c(media, elements[length(elements)])
}
genotypes = unique(genotypes)
genotypes
#media
```

Take files from natural isolates
```{r}
report = data.frame(files)
report$samplesize = NA; report$R=NA; report$t0=NA; report$n=NA; report$G=NA; 
#report$longfilename=NA; 
```

# Explore the fitting outcomes of 'flexsurv'. 

```{r}
i=2
 # tb = read.table( paste("../qinlab_rls/",files[i],sep=''), sep="\t")
  tb = read.csv( paste(mydir,"/",files[i] ,sep=''), sep="\t")
  GompFlex = flexsurvreg(formula = Surv(tb[,1]) ~ 1, dist = 'gompertz')
  WeibFlex = flexsurvreg(formula = Surv(tb[,1]) ~ 1, dist = 'weibull')
#str(GompFlex)
GompFlex$res
GompFlex$res.t
GompFlex$opt$hessian
#str(WeibFlex)
```

# Now, fit all RLS data sets by strains

```{r, message=FALSE }
for( i in 1:length(report[,1])){
#for( i in 3:4){
  tb = read.csv( paste(mydir,"/",files[i] ,sep=''), sep="\t")
  #tb = read.table( paste("../qinlab_rls/",my.files[1],sep=''), sep="\t")
  report$samplesize[i] = length(tb[,1])

  GompFlex = flexsurvreg(formula = Surv(tb[,1]) ~ 1, dist = 'gompertz')
  WeibFlex = flexsurvreg(formula = Surv(tb[,1]) ~ 1, dist = 'weibull')

  report$avgLS[i] =  mean(tb[,1])
  report$stdLS[i] =  sd(tb[,1])
  report$CV[i] = report$stdLS[i] / report$avgLS[i]

  report$GompGFlex[i] = GompFlex$res[1,1]
  report$GompRFlex[i] = GompFlex$res[2,1]
  report$GompLogLikFlex[i] = round(GompFlex$loglik, 1)
  report$GompAICFlex[i] = round(GompFlex$AIC)

  report$WeibShapeFlex[i] = WeibFlex$res[1,1]
  report$WeibRateFlex[i] = WeibFlex$res[2,1]
  report$WeibLogLikFlex[i] = round(WeibFlex$loglik, 1)  
  report$WeibAICFlex[i] = round(WeibFlex$AIC)

  #set initial values
  Rhat = report$GompRFlex[i]; # 'i' was missing. a bug costed HQ a whole afternoon.
  Ghat = report$GompGFlex[i];
  nhat = 6;  
  t0= (nhat-1)/Ghat;
  fitBinom = optim ( c(Rhat, t0, nhat),  llh.binomialMortality.single.run, 
                     lifespan=tb[,1], 
                     #method='SANN') #SANN needs control  
                     method="L-BFGS-B", 
                     lower=c(1E-10, 1, 1), upper=c(1,200,20) );  
  report[i, c("R", "t0", "n")] = fitBinom$par[1:3]
  report$G[i] = (report$n[i] - 1)/report$t0[i]
}
```

Show the results
```{r}
#report[ grep("tBY", report$strains), ]
report
```


Output
```{r}
write.csv(report, file = paste('sandbox/_report_', mydir, '.csv', sep='' ), row.names = FALSE)

```




