---
title: "Mediation test on natural isolates. short version"
author: "h qin"
date: "June 13, 2017"
output:
  html_document: default
  pdf_document: default
---


```{r}
rm(list=ls())
set.seed(20170101)
library('flexsurv')
source("../lifespan.r")
```

# Load boostrapped fitting results

```{r}
report = read.csv("sandbox/Bootstrap_summary.csv")
```

```{r}
summary(lm(log10(report$GompRFlex) ~ report$GompGFlex))
summary(lm(log10(report$R) ~ report$GompGFlex))
summary(lm(log10(report$R) ~ report$G)) #G from t0 and n 
summary(lm(report$GompGFlex ~ report$G)) #good agreement bwteen GFlex and G from binomial modeling

summary(lm(log10(report$R) ~ report$t0)) #G from t0 and n 
summary(lm(log10(report$R) ~ report$n)) #G from t0 and n 

```


# Mediation test on Gflex <--t0 <-- RFlex
# Hong thinks the results indicate the t0 is the mediator from Flex to GFlex, but not sure.  

```{r}
library(mediation)
set.seed(20170801)
report$log10GompRFlex = log10(report$GompRFlex)
med.fit = lm(t0 ~ log10GompRFlex, data=report)  
summary(med.fit)
out.fit = lm(GompGFlex ~ t0 + log10GompRFlex, data=report)  
summary(out.fit)
med.out <- mediate(med.fit, out.fit, treat = "log10GompRFlex", mediator = "t0", robustSE = TRUE, sims = 100)
summary(med.out)

```

# Mediation test 2 on Rflex <--t0 <-- GFlex
#Hong thinks this is negative result, which means t0 works only in one direction. 

```{r}
med.fit = lm(t0 ~ GompGFlex, data=report)  
summary(med.fit)
out.fit = lm(log10GompRFlex ~ t0 + GompGFlex, data=report)  
summary(out.fit)
med.out <- mediate(med.fit, out.fit, treat = "GompGFlex", mediator = "t0", robustSE = TRUE, sims = 100)
summary(med.out)


```


#overlay binomial aging model cuvrve with RLS data

